language: python
python: 2.7
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install pytest-mock
  - pip install requests
  - pip install prospector==1.2.0
  - pip install codecov
  - pip install -r requirements.txt
script:
  - prospector
  - pytest --cov=./ --cov-report=xml
after_success:
  - codecov
